USE [master]
GO
ALTER DATABASE [AccessSettings] SET READ_WRITE WITH NO_WAIT
GO
ALTER DATABASE [lutfi_test] SET READ_WRITE WITH NO_WAIT
GO
ALTER DATABASE [NavPlus] SET READ_WRITE WITH NO_WAIT
GO


/*
USE [master]
GO
ALTER DATABASE [lutfi_test] SET READ_ONLY WITH NO_WAIT
GO
*/